### ISSUE TITLE
problem while running the training code

### ISSUE THREAD

**Issue by zelonghaha** [thohemp/6DRepNet#2]
I have the following problem while running the training code, can you help me？Thanks very much!
Traceback (most recent call last):
  File "/home/zelong/D/testdemo/6DRepNet/train.py", line 112, in <module>
    model = SixDRepNet(backbone_name='RepVGG-B1g2',
  File "/home/zelong/D/testdemo/6DRepNet/model.py", line 19, in __init__
    checkpoint = torch.load(backbone_file)
  File "/home/zelong/anaconda3/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/zelong/anaconda3/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/zelong/anaconda3/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'RepVGG-B1g2-train.pth'

**Comment by thohemp** [comment]
Yes, this is easily sorted out. You need to download the pretrained repvgg backbone models.
Here: https://drive.google.com/drive/folders/1Avome4KvNp0Lqh2QwhXO6L5URQjzCjUq
Download "RepVGG-B1g2-train.pth" and save it in the root directory. Then, try again.
