### ISSUE TITLE
cant change gpu id in demo.py

### ISSUE THREAD

**Issue by soroush-mim** [thohemp/6DRepNet#26]
there is a cuda error when changing gpu to another id(except 0)

`Traceback (most recent call last):
  File "demo.py", line 136, in <module>
    R_pred = model(img)
  File "/mnt/data2/head_pose_estimation/codes/6DRepNet/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data2/head_pose_estimation/codes/6DRepNet/model.py", line 48, in forward
    return utils.compute_rotation_matrix_from_ortho6d(x)
  File "/mnt/data2/head_pose_estimation/codes/6DRepNet/utils.py", line 146, in compute_rotation_matrix_from_ortho6d
    x = normalize_vector(x_raw, use_gpu) #batch*3
  File "/mnt/data2/head_pose_estimation/codes/6DRepNet/utils.py", line 119, in normalize_vector
    v_mag = torch.max(v_mag, torch.autograd.Variable(torch.FloatTensor([1e-8]).cuda()))
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:3 and cuda:0! `

**Comment by thohemp** [comment]
This should work: `CUDA_VISIBLE_DEVICES=3 demo.py`
