### ISSUE TITLE
Pip install failed

### ISSUE THREAD

**Issue by GlennCGL** [thohemp/6DRepNet#29]
When I install the package: pip install SixDRepNet, it returns
Collecting SixDRepNet
  Downloading SixDRepNet-0.1.1.tar.gz (23 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/5l/9fsdwp_n1td91scw10n67zwc0000gp/T/pip-install-8xwcmbp1/sixdrepnet_2b06c43f46c5428d9c99677633d23b6e/setup.py", line 23, in <module>
          long_description="".join(open("README.MD", "r").readlines()),
      FileNotFoundError: [Errno 2] No such file or directory: 'README.MD'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by GlennCGL** [comment]
And demo can not run successfully: python SixDRepNet/demo.py --snapshot 6DRepNet_300W_LP_AFLW2000.pth --cam 0
it return segmentation fault

**Comment by GlennCGL** [comment]
I have fixed problem above.
Nice work and demo!
